#!/usr/bin/with-contenv bash

# replace values in /config/.minetest/main-config/minetest.conf by environment variables
echo "------------------------------------------"
echo "replace values in /config/.minetest/main-config/minetest.conf by environment variables"
# server_name
if [ -z "$SERVER_NAME" ]; 
    then echo "SERVER_NAME not given"; 
    else sed -i "s/.*server_name.*/server_name = $SERVER_NAME/" /config/.minetest/main-config/minetest.conf;
fi

if [ -z "$SERVER_DESCRIPTION" ]; 
    then echo "SERVER_DESCRIPTION not given"; 
    else sed -i "s/.*server_description.*/server_description = $SERVER_DESCRIPTION/" /config/.minetest/main-config/minetest.conf;
fi

# server_announce = false
sed -e "s/.*server_announce.*/server_announce = false/"

# motd = "Welcome to the training"
if [ -z "$MOTD" ]; 
    then echo "MOTD not given"; 
    else sed -i "s/.*motd.*/motd = $MOTD/" /config/.minetest/main-config/minetest.conf;
fi
# max_users 
if [ -z "$MAX_USERS" ]; 
    then echo "MAX_USERS not given"; 
    else sed -i "s/.*max_users.*/max_users = $MAX_USERS/" /config/.minetest/main-config/minetest.conf;
fi

# to be checked since not available on server 
# creative_mode
sed -i "s/.*creative_mode.*/creative_mode = true/" /config/.minetest/main-config/minetest.conf

# default_password
if [ -z "$PASSWORD" ]; 
    then echo "PASSWORD not given"; 
    else sed -i "s/.*default_password.*/default_password = $PASSWORD/" /config/.minetest/main-config/minetest.conf;
fi
# enable_damage = false
sed -i "s/.*enable_damage.*/enable_damage = false/" /config/.minetest/main-config/minetest.conf
# enable_pvp = false
sed -i "s/.*enable_pvp.*/enable_pvp = false/" /config/.minetest/main-config/minetest.conf

# default privileges
sed -i "s/.*default_privs.*/default_privs = interact, shout, fly, teleport/" /config/.minetest/main-config/minetest.conf

# day/night cycle
sed -i "s/.*time_speed.*/time_speed = 0/" /config/.minetest/main-config/minetest.conf

# time of day when a new world is created
sed -i "s/.world_start_time.*/world_start_time = 6125/" /config/.minetest/main-config/minetest.conf

# admins
if [ -z "$ADMIN" ]; 
    then echo "ADMIN not given"; 
    else 
        sed -i "s/# name.*/name = $ADMIN/" /config/.minetest/main-config/minetest.conf;
        sed -i "s/^name.*/name = $ADMIN/" /config/.minetest/main-config/minetest.conf;
fi
# mapgen
if [ -z "$MAPGEN" ]; 
    then echo "MAPGEN not given"; 
    else sed -i "s/.*mg_name.*/mg_name = $MAPGEN/" /config/.minetest/main-config/minetest.conf;
fi

# permissions
chown -R abc:abc \
    /config

echo "------------------------------------------"