#!/usr/bin/with-contenv bash
echo "------------------------------------------"

if [ -z "$MOD_PATH" ]; 
    then echo "MOD_PATH not given"; 
    else 
        echo "copy mods from /home/mods to ${MOD_PATH}";
        cp -R /home/mods ${MOD_PATH};
fi

echo "------------------------------------------"